#!/usr/bin/node

const http=require('http'),
      path=require('path'),
      fs=require('fs');
      util=require('util'),
      log=util.debuglog("wd");

var file;
//console.log(123)
http.createServer((req,res)=>{

console.log(req.readers,req.url);

  file=path.join(__dirname,req.url);

  console.log(file);

var read=fs.createReadStream(file);
read.on('error',(err)=>{   res.end(err.messsage);
    return;
  });
  read.pipe(res);
}).listen(8080)
